USE `CUSTOMER_DB`; 
DROP PROCEDURE IF EXISTS NCGA;
DROP TABLE IF EXISTS NCG;
DELIMITER //
CREATE PROCEDURE NCGA(IN str varchar(6))
BEGIN
    DECLARE done INT DEFAULT 0;
	DECLARE `CUST_NAME` varchar(40);
	DECLARE `CUST_COUNTRY` varchar(20);
	DECLARE `GRADE` decimal(10,0);
	DECLARE `AGENT_CODE` varchar(6);
    DECLARE cur CURSOR FOR

        SELECT c.CUST_NAME, c.CUST_COUNTRY, c.GRADE, c.AGENT_CODE
        FROM customer c;
        -- WHERE c.AGENT_CODE LIKE 'A00%';
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
    
	CREATE TABLE NCG (
	`CUST_NAME` varchar(40),
	`CUST_COUNTRY` varchar(20),
	`GRADE` decimal(10,0)
	);

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO CUST_NAME, CUST_COUNTRY, GRADE, AGENT_CODE;
        IF done THEN
            LEAVE read_loop;
        END IF;
		IF AGENT_CODE LIKE str THEN
			INSERT INTO NCG (`CUST_NAME`, `CUST_COUNTRY`, `GRADE`) VALUES (CUST_NAME, CUST_COUNTRY, GRADE);
		END IF;
    END LOOP;
    CLOSE cur;
END;
//
DELIMITER ;

CALL NCGA('A00%'); 
SELECT * FROM NCG;
