#include <iostream>
#include <cstring>
#include <cstdlib>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <algorithm>  
#include <cctype>     
#include <vector>
#include <fstream>
#include <sstream>
#include <fcntl.h>
#include <sys/stat.h>
#include <cerrno>
#include <dirent.h>
#include <cstring>
#include <pwd.h>
#include <grp.h>
#include <ctime>
#include <iomanip>
#include <string>
#include <csignal>
#include <termios.h>
